import streamlit as st
from openai import OpenAI

# Initialize OpenAI client and set the API key from Streamlit secrets
openai_api_key = st.secrets["OPENAI_API_KEY"]
openai = OpenAI(api_key=openai_api_key)

def generate_image_with_dalle3(client, prompt):
    response = client.images.generate(
        model="dall-e-3",
        prompt=prompt,
        size="1024x1024",
        quality="standard",
        n=1,
    )
    image_url = response.data[0].url
    return image_url

def main():
    st.title("DALL-E 3 Image Generator")
    
    prompt = st.text_input("Enter a description for the image:")
    
    if st.button("Generate Image"):
        if not prompt:
            st.error("Please enter a description for the image.")
        else:
            with st.spinner("Generating image..."):
                try:
                    image_url = generate_image_with_dalle3(openai, prompt)
                    st.image(image_url, caption="Generated by DALL-E 3", use_column_width=True)
                except Exception as e:
                    st.error(f"An error occurred: {e}")

if __name__ == "__main__":
    main()