import streamlit as st
import openai
import requests
from io import BytesIO
from PIL import Image

# Initialize OpenAI client and set the API key
openai.api_key = st.secrets["OPENAI_API_KEY"]

# Initialize the client
client = openai.Image

def generate_image(client, model_choice, prompt):
    response = client.generate(
        model=model_choice,
        prompt=prompt,
        size="1024x1024",
        quality="standard",
        n=1
    )
    image_url = response.data[0].url
    return image_url

def main():
    st.title("DALL-E Image Generator")
    
    model_choice = "image-alpha-001"  # You can update this if there are different models available
    prompt = st.text_input("Enter a description for the image:")
    
    if st.button("Generate Image"):
        with st.spinner("Generating image..."):
            image_url = generate_image(client, model_choice, prompt)
            response = requests.get(image_url)
            img = Image.open(BytesIO(response.content))
            st.image(img, caption="Generated by DALL-E", use_column_width=True)

if __name__ == "__main__":
    main()
