import streamlit as st
from openai import OpenAI
import requests
from io import BytesIO
from PIL import Image

# Initialize OpenAI client and set the API key from Streamlit secrets
openai = OpenAI(api_key=st.secrets["OPENAI_API_KEY"])

def generate_image(prompt):
    response = openai.images.create(
        model="image-alpha-001",  # DALL-E 2 model
        prompt=prompt,
        size="1024x1024",
        n=1
    )
    image_url = response['data'][0]['url']
    return image_url

def main():
    st.title("DALL-E Image Generator")
    
    prompt = st.text_input("Enter a description for the image:")
    
    if st.button("Generate Image"):
        with st.spinner("Generating image..."):
            image_url = generate_image(prompt)
            response = requests.get(image_url)
            img = Image.open(BytesIO(response.content))
            st.image(img, caption="Generated by DALL-E", use_column_width=True)

if __name__ == "__main__":
    main()